### ISSUE TITLE
[Request] Prometheus monitoring

### ISSUE THREAD

**Issue by jmreicha** [rancher/compose-templates#24]
It would be cool to have a stack that runs some combination of stat collector (cadvisor), aggregator (Prometheus), and dashboard (Grafana or promdash) for viewing.

**Comment by cloudnautique** [comment]
Agreed, it's on a very long list :) we are running cadvisor as part of rancher now, just not storing the data.

**Comment by DanielDent** [comment]
I've done an initial release of just such a stack: https://github.com/DanielDent/cowhand. It's setup as a Rancher Catalog.

Prometheus + Grafana + Cadvisor + node-exporter + InfluxDB, with some service discovery glue to have Prometheus automatically pick up and label things to monitor.

I would welcome comments/suggestions/pull requests.

**Comment by jmreicha** [comment]
Can't wait to try this out, nice job.

**Comment by deniseschannon** [comment]
@DanielDent Feel free to make a PR in the community catalog so others could use it. :) https://github.com/rancher/community-catalog

**Comment by Rucknar** [comment]
@jmreicha Should now be in the community catalog for Prometheus :)

**Comment by orlando** [comment]
Should we close this issue?, Prometheus is already in the catalog
